export const localCatMemes = [
  "https://i.imgur.com/3Z3Z3Z3.jpeg",
  "https://i.imgur.com/4Z4Z4Z4.jpeg",
  "https://i.imgur.com/5Z5Z5Z5.jpeg",
  "https://i.imgur.com/6Z6Z6Z6.jpeg",
  "https://i.imgur.com/7Z7Z7Z7.jpeg",
  "https://i.imgur.com/8Z8Z8Z8.jpeg",
  "https://i.imgur.com/9Z9Z9Z9.jpeg",
  "https://i.imgur.com/AZAZAZA.jpeg",
  "https://i.imgur.com/BZbZbZb.jpeg",
  "https://i.imgur.com/CZCZCZC.jpeg",
  "https://i.imgur.com/DZDZDZD.jpeg",
  "https://i.imgur.com/EZEZEZE.jpeg",
  "https://i.imgur.com/FZFZFZF.jpeg",
  "https://i.imgur.com/GZgZgZg.jpeg",
  "https://i.imgur.com/HZHZHZH.jpeg",
  "https://i.imgur.com/IZIZIZI.jpeg",
  "https://i.imgur.com/JZJZJZJ.jpeg",
  "https://i.imgur.com/KZKZKZK.jpeg",
  "https://i.imgur.com/LZLZLZL.jpeg",
  "https://i.imgur.com/MZMZMZM.jpeg",
];

export const localBabyYodaMemes = [
  "https://i.imgur.com/1Y1Y1Y1.jpeg",
  "https://i.imgur.com/2Y2Y2Y2.jpeg",
  "https://i.imgur.com/3Y3Y3Y3.jpeg",
  "https://i.imgur.com/4Y4Y4Y4.jpeg",
  "https://i.imgur.com/5Y5Y5Y5.jpeg",
  "https://i.imgur.com/6Y6Y6Y6.jpeg",
  "https://i.imgur.com/7Y7Y7Y7.jpeg",
  "https://i.imgur.com/8Y8Y8Y8.jpeg",
  "https://i.imgur.com/9Y9Y9Y9.jpeg",
  "https://i.imgur.com/AYAYAYA.jpeg",
  "https://i.imgur.com/BYBYBYB.jpeg",
  "https://i.imgur.com/CYCYCYC.jpeg",
  "https://i.imgur.com/DYDYDYD.jpeg",
  "https://i.imgur.com/EYEYEYE.jpeg",
  "https://i.imgur,com/FYFYFYF.jpeg",
  "https://i.imgur.com/GYGYGYG.jpeg",
  "https://i.imgur.com/HYHYHYH.jpeg",
  "https://i.imgur.com/IYIYIYI.jpeg",
  "https://i.imgur.com/JYJYJYJ.jpeg",
  "https://i.imgur.com/KYKYKYK.jpeg",
];

export const localDadJokes = [
  "I'm afraid for the calendar. Its days are numbered.",
  "My wife said I should do lunges to stay in shape. That would be a big step forward.",
  "Why do fathers take an extra pair of socks when they go golfing? In case they get a hole in one!",
  "Singing in the shower is fun until you get soap in your mouth. Then it's a soap opera.",
  "What do a tick and the Eiffel Tower have in common? They're both Paris sites.",
  "What do you call a fish wearing a bowtie? Sofishticated.",
  "How do you follow Will Smith in the snow? You follow the fresh prints.",
  "If April showers bring May flowers, what do May flowers bring? Pilgrims.",
  "I thought the dryer was shrinking my clothes. Turns out it was the refrigerator all along.",
  "What's the best time to go to the dentist? Tooth-hurty.",
  "I used to be addicted to soap, but I'm clean now.",
  "A ham sandwich walks into a bar and orders a beer. The bartender says, 'Sorry we don't serve food here.'",
  "I've got a great joke about construction, but I'm still working on it.",
  "I was going to tell a time-traveling joke, but you guys didn't like it.",
  "I'm on a seafood diet. I see food and I eat it.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "I made a pencil with two erasers. It was pointless.",
  "I've just written a book on reverse psychology. Do not read it.",
  "I've been trying to come up with a dad joke about getting a haircut, but I'm not sure where to start.",
  "I'm so good at sleeping, I can do it with my eyes closed.",
];